/** Declaration file generated by dts-gen */

export = dirty_reprojectors;

declare function dirty_reprojectors(options: any, geometry: any): any;

declare namespace dirty_reprojectors {
    const prototype: {
    };

}

